# Generated by Django 3.2 on 2021-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_auto_20210512_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
