# Generated by Django 3.2 on 2021-05-12 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0005_auto_20210512_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
